### PR TITLE
add skip_filter alias

### PR DESCRIPTION
**Pull request by grosser**
@pschambacher 

technically a bad idea to use this, but we should add it anyway ...

### CODE REVIEW

**Comment by pschambacher** [comment]
:+1:

**Comment by grosser** [comment]
then merge it :D

**Comment by pschambacher** [comment]
Will do in a bit. Also give you access.

**Comment by pschambacher** [comment]
@grosser v0.2.0. You're now collaborator and you have permissions on rubygems.

**Pull request merged**
